<?php
    return [
        'host_url' => '46.148.14.55',
        'long_name' => 'Akademia Śląska &mdash; TEST Server',
        'menu_items' => [
            ['url' => '/phpmyadmin', 'label' => 'phpMyAdmin'],
        ],
        'short_name' => 'TEST Server',
        'description' => 'Serwer <strong>testowy</strong> służy do testowania aplikacji webowych tworzonych w Akademii Śląskiej &mdash; przeznaczony jest dla <strong>użytkowników technicznych</strong> (testerów). Bazy danych to najczęściej <em>nieskładny śmietnik</em>, ale wprowadzane do nich zmiany <strong>są zachowywane</strong> pomiędzy sesjami.',
        'buttons' => [
            ['url' => 'planner.html', 'label' => 'asPlan'],
        ],
        'footer' => 'Dostęp do serwera możliwy jest na trzy sposoby: ',
        'links' => [
            'http://test.as.ftp.sh/',
            'http://10.0.2.34/',
            'http://93.179.198.180/',
        ],
    ];
?>